version: '3.9'
services:
  postgres:
    image: timescale/timescaledb-ha:pg15-latest
    environment:
      POSTGRES_PASSWORD: vectorbit
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d

  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - ../.env

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
